{
 "title": "shelly1",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "device",
    "query": "select distinct device from 'shelly_meter1'\n"
   },
   {
    "name": "idx",
    "query": "select distinct idx from 'shelly_meter1' where device = '$device'"
   },
   { "name": "interval", "label": "consumption interval", "query": "10m,30m,1h,1d,7d,30d" }
  ]
 },
 "panels": [
  {
   "title": "total power consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_meter1b as (\n        select timestamp, total\n        from 'shelly_meter1'\n        where device = '$device' and idx = '$idx' and is_valid = true and $__timeFilter(timestamp)\n    )\nselect cast(0 as timestamp) time, nsum(consumption)*(1.0/60.0) as value\nfrom (\n    select (case when t1.total >= t2.total then t1.total-t2.total else null end) as consumption\n    from shelly_meter1b t1\n    lt join shelly_meter1b t2\n)"
    }
   ]
  },
  {
   "title": "power measurement failure rate",
   "type": "gauge",
   "description": "percentage of is_valid=false",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_meter1b as (\n        select timestamp, is_valid\n        from 'shelly_meter1'\n        where device = '$device' and idx = '$idx' and $__timeFilter(timestamp)\n    ),\n    count_all as (\n        select count() as value\n        from shelly_meter1b\n    ),\n    count_not_valid as (\n        select count() as value\n        from shelly_meter1b\n        where is_valid = false\n    )\nselect \n    cast(0 as timestamp) time,\n    ((1.0*count_not_valid.value)/count_all.value) as value\nfrom count_all\ncross join count_not_valid"
    }
   ]
  },
  {
   "title": "power consumption ",
   "type": "timeseries",
   "description": "sampled by \"consumption interval\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "with\n    shelly_meter1b as (\n        select timestamp, total\n        from 'shelly_meter1'\n        where device = '$device' and idx = '$idx' and is_valid = true and $__timeFilter(timestamp)\n    ),\n    interval_s as (\n        select (case\n            when '$interval' like '%s' then cast(left('$interval', -1) as int)*1\n            when '$interval' like '%m' then cast(left('$interval', -1) as int)*60\n            when '$interval' like '%h' then cast(left('$interval', -1) as int)*3600\n            when '$interval' like '%d' then cast(left('$interval', -1) as int)*86400\n            else 0 end\n        ) as value\n    )\nselect timestamp as time, nsum(consumption)*(1.0/60.0) as value\nfrom (\n    select t1.timestamp, \n    (case\n        when datediff('s', t1.timestamp, t2.timestamp) > interval_s.value then null\n        when t1.total >= t2.total then t1.total-t2.total\n        else null end) as consumption\n    from shelly_meter1b t1\n    lt join shelly_meter1b t2\n    cross join interval_s\n)\nsample by $interval align to calendar "
    }
   ]
  },
  {
   "title": "device temp measurement failure rate",
   "type": "gauge",
   "description": "percentage of is_valid=false",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_temperature1b as (\n        select timestamp, is_valid\n        from 'shelly_temperature1'\n        where device = '$device' and $__timeFilter(timestamp)\n    ),\n    count_all as (\n        select count() as value\n        from shelly_temperature1b\n    ),\n    count_not_valid as (\n        select count() as value\n        from shelly_temperature1b\n        where is_valid = false\n      )\nselect \n    cast(0 as timestamp) time,\n    ((1.0*count_not_valid.value)/count_all.value) as value\nfrom count_all\ncross join count_not_valid"
    }
   ]
  },
  {
   "title": "device temp overtemperature rate",
   "type": "gauge",
   "description": "percentage of overtemperature=false",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with\n    shelly_temperature1b as (\n        select timestamp, overtemperature\n        from 'shelly_temperature1'\n        where device = '$device' and is_valid = true and $__timeFilter(timestamp)\n    ),\n    count_all as (\n        select count() as value\n        from shelly_temperature1b\n    ),\n    count_overtemperature as (\n        select count() as value\n        from shelly_temperature1b\n        where overtemperature = true\n    )\nselect \n    cast(0 as timestamp) time,\n    ((1.0*count_overtemperature.value)/count_all.value) as value\nfrom count_all\ncross join count_overtemperature"
    }
   ]
  },
  {
   "title": "wattmeter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(power) as power\nfrom 'shelly_meter1'\nwhere\n    device = '$device'\n    and idx = '$idx'\n    and is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval"
    },
    {
     "rawSql": "with\n    shelly_meter1b as (\n        select timestamp, total\n        from 'shelly_meter1'\n        where device = '$device' and idx = '$idx' and is_valid = true and timestamp between dateadd('m', -15, $__timeFrom()) and $__timeTo()\n    )\nselect\n    time, \n    (case\n        when total_is_ordered then ((((total_max-total_min)*(1.0/60.0))/datediff('s', timestamp_min, timestamp_max))*3600.0)\n        else null end\n    ) as avgPowerInThePrecedingQuarterHour\nfrom (\n    select\n        timestamp as time,\n        first(total) as total_min,\n        last(total) as total_max,\n        isOrdered(cast(total AS long)) as total_is_ordered,\n        first(time2) as timestamp_min,\n        last(time2) as timestamp_max\n    from (\n        select\n            t1.timestamp,\n            t2.timestamp as time2,\n            first(t2.total) as total\n        from shelly_meter1b t1\n        inner join shelly_meter1b t2\n        on t2.timestamp between dateadd('m', -15, t1.timestamp) and t1.timestamp\n        where $__timeFilter(t1.timestamp)\n        sample by $__interval\n    ) timestamp(timestamp)\n) timestamp(time)"
    },
    {
     "rawSql": "with\n    shelly_meter1b as (\n        select timestamp, total\n        from 'shelly_meter1'\n        where device = '$device' and idx = '$idx' and is_valid = true and timestamp between dateadd('m', -60, $__timeFrom()) and $__timeTo()\n    )\nselect\n    time, \n    (case\n        when total_is_ordered then ((((total_max-total_min)*(1.0/60.0))/datediff('s', timestamp_min, timestamp_max))*3600.0)\n        else null end\n    ) as avgPowerInThePrecedingHour\nfrom (\n    select\n        timestamp as time,\n        first(total) as total_min,\n        last(total) as total_max,\n        isOrdered(cast(total AS long)) as total_is_ordered,\n        first(time2) as timestamp_min,\n        last(time2) as timestamp_max\n    from (\n        select\n            t1.timestamp,\n            t2.timestamp as time2,\n            first(t2.total) as total\n        from shelly_meter1b t1\n        inner join shelly_meter1b t2\n        on t2.timestamp between dateadd('m', -60, t1.timestamp) and t1.timestamp\n        where $__timeFilter(t1.timestamp)\n        sample by $__interval\n    ) timestamp(timestamp)\n) timestamp(time)"
    }
   ]
  },
  {
   "title": "device temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(tc) as tc,\n    (case when overtemperature then 1 else 0 end) as overtemperature\nfrom 'shelly_temperature1'\nwhere\n    device = '$device'\n    and is_valid = true\n    and $__timeFilter(timestamp)\nsample by $__interval"
    }
   ]
  }
 ]
}