{
 "title": "shellyht2",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "device_id",
    "query": "select distinct device_id from shelly_ht_meter2 where $__timeFilter(timestamp)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "current temperature",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select last(temp) as temp, cast(0 as timestamp) as time\nfrom shelly_ht_meter2\nwhere device_id = '$device_id' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "current humidity",
   "type": "stat",
   "description": "last measurement",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select last(hum) as hum, cast(0 as timestamp) as time\nfrom shelly_ht_meter2\nwhere device_id = '$device_id' and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(temp) as temp\nfrom shelly_ht_meter2\nwhere\n    device_id = '$device_id'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  },
  {
   "title": "humidity measurements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select \n    timestamp as time,\n    avg(hum) as hum\nfrom shelly_ht_meter2\nwhere\n    device_id = '$device_id'\n    and $__timeFilter(timestamp)\nsample by $__interval fill(null)"
    }
   ]
  }
 ]
}